theme:
  features:
    - search.suggest
    - search.highlight
    - search.share
    - navigation.footer
  logo: assets/Logo.png
  favicon: https://novilock.ru/image/catalog/Finger-grey.png
  name: material
  icon:
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
plugins:
  - search:
      lang: 
        - en
        - ru
  - offline
  - privacy
